# Variables for GA
POPULATION_SIZE = 100
ITERATIONS = 10
CROSSOVER_PROB = 0.5
MUTATION_PROB = 0.1
TOURNAMENT_SIZE = 20

# Weight variables
INTERSECTION_WEIGHT = 50
PATHS_LENGTH_WEIGHT = 1
SEGMENTS_NUMBER_WEIGHT = 1
NUMBER_OF_PATHS_OUTSIDE_BOARD_WEIGHT = 50

# Path to file with problem
FILE = 'Tests/zad1.txt'
